# Create ~/.config/nvim/
- name: Create directory for nvim
  file:
    path: ~/.config/nvim
    state: directory
    mode: u=rwx,g=rx,o-rwx
    owner: zvekovius
    group: zvekovius

- name: Add nvim configuration
  copy:
    src: ../files/init.vim
    dest: ~/.config/nvim/init.vim
    owner: zvekovius
    group: zvekovius
    mode: u=rwx,g=rx,o-rwx

- name: Create plugin dirs
  file:
    path: ~/.config/nvim/bundle
    state: directory
    mode: u=rwx,g=rx,o-rwx
    owner: zvekovius
    group: zvekovius

- name: Checkout Vundle
  git:
    repo: 'https://github.com/VundleVim/Vundle.vim'
    dest: ~/.config/nvim/bundle/Vundle.vim

# Not really idempotent. But PluginInstall will no-op if nothing to do.
# Have to deal with "changed" forever on this one.
- name: Install vim plugins
  shell: vim +PluginInstall +qall

